database:
  type: sqlite #mysql or sqlite is supported
  username: "root"
  password: "password"
  database: "AnturniaQuests"
  ip: "127.0.0.1"
  port: 3306

commands:
  - name: "quests"
    aliases:
      - "quest"

questMenuEnabled: true
storylinesEnabled: true

debug: true