name: AnturniaQuests
version: '${project.version}'
main: de.frinshhd.anturniaquests.Main
api-version: '1.16'
author: "FrinshHD"
softdepend: [ "Vault", "FancyNpcs", "Citizens" ]

commands:
  quests:
    description: open the quests menu,
    aliases: [ "anturniaquests" ]

permissions:
  quests.open:
    default: true
  quests.admin.reload:
    default: op
  quests.help:
    default: true
  quests.admin.updateNotify:
    default: op