name: AnturniaQuests
version: '${project.version}'
main: de.frinshhd.anturniaquests.Main
api-version: '1.16'
author: "FrinshHD"
softdepend: [ "Vault", "FancyNpcs", "Citizens" ]

commands:
  quests:
    description: open the quests menu,
    aliases: [ "anturniaquests" ]

permissions:
  anturniaquests.command.open:
    default: true
  anturniaquests.command.help:
    default: true
  anturniaquests.command.version:
    default: true
  anturniaquests.command.admin.reload:
    default: op
  anturniaquests.admin.updateNotify:
    default: op