name: AnturniaQuests
version: '${project.version}'
main: de.frinshhd.anturniaquests.Main
api-version: '1.16'
author: "FrinshHD"
softdepend: [ "Vault", "FancyNpcs", "Citizens", "PlaceholderAPI" ]

permissions:
  anturniaquests.command.open:
    default: true
  anturniaquests.command.help:
    default: true
  anturniaquests.command.version:
    default: true
  anturniaquests.command.admin.reload:
    default: op
  anturniaquests.command.admin.reset:
    default: op
  anturniaquests.command.admin.itemInfo:
    default: op
  anturniaquests.admin.updateNotify:
    default: op
  anturniaquests.command.admin.storylines:
    default: op
  anturniaquests.command.admin.storylines.reset:
    default: op